---
# tasks file for web-stg
- name: Create an IP address for first instance
  gcp_compute_address:
    name: "{{ vm_name }}-ip"
    region: "{{ region }}"
    project: "{{ gcp_project }}"
    service_account_file: "{{ credentials_file }}"
    auth_kind: "{{ auth_kind }}"
  register: gcea_ip
  when: inventory_hostname in groups['local']

- name: Bring up the first instance in the first zone.
  gcp_compute_instance:
    name: "{{ vm_name }}"
    machine_type: "{{ machine_type }}"
    disks:
      - auto_delete: true
        boot: true
        initialize_params:
          disk_size_gb: 30
          source_image: "{{ image }}"
    network_interfaces:
      - access_configs:
          - name: External NAT
            nat_ip: "{{ gcea_ip }}"
            type: ONE_TO_ONE_NAT
    tags:
      items:
        - http-server
        - https-server
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    service_account_file: "{{ credentials_file }}"
    auth_kind: "{{ auth_kind }}"
  register: gcea
  when: inventory_hostname in groups['local']

- name: Wait for SSH for instances in first zone
  wait_for: delay=1 host={{ gcea_ip.address }} port=22 state=started timeout=30
  when: inventory_hostname in groups['local']
- name: Save host data for first zone
  add_host: hostname={{ gcea_ip.address }} groupname=gce_instances_ips
  when: inventory_hostname in groups['local']

- name: Set a hostname
  hostname:
    name: "{{ new_hostname }}" 
  when: (hostname_change  == true)


- name: install apache
  apt:
    name: apache2
    state: latest
  when: ('vm_name in ansible_facts.fqdn' ) or (ansible_facts['hostname'] ==  new_hostname) 

- name: start the service
  service:
    name: apache2
    state: started
    enabled: true
  when: ('vm_name in ansible_facts.fqdn' ) or (ansible_facts['hostname'] ==  new_hostname)

- name: copy files
  template:
    src: html.j2
    dest: /var/www/html/index.html
  notify: restart apache
  when: ('vm_name in ansible_facts.fqdn' ) or (ansible_facts['hostname'] ==  new_hostname)
